source:      .
destination: ./_site
baseurl:     /dalap-html.docs
package_version: "0.1.0"
plugins:     ./_plugins
auto: true
exclude: [bin, CNAME, Gemfile, Gemfile.lock, README.md]
markdown: rdiscount
permalink: /:title
